### ISSUE TITLE
dove

### ISSUE THREAD

**Issue by alterfang** [getgridea/site#11]
## 主题名称 / Theme Name
- dove

## 介绍 / Introduction
- 

## 仓库地址 / Github Repo
- https://github.com/alterfang/gridea-theme-dove

## 预览地址 / Preview Address
-

## 截图 / Screenshots
-![首页](https://www.z4a.net/images/2019/08/22/b8766b4dcafc83416f16897b5104d867.jpg)

**Comment by EryouHao** [comment]
通过访问，发现仓库已消失，暂时关掉了就。
