### ISSUE TITLE
hexo-theme-melody

### ISSUE THREAD

**Issue by paynexss** [getgridea/site#22]
## 主题名称 /
-  hexo-theme-melody

## 介绍 /
-  我不是作者，望大佬收录哈

## 仓库地址 / 
- https://github.com/Molunerfinn/hexo-theme-melody.git

## 预览地址 / 
-https://molunerfinn.com/

## 截图 / Screenshots
- 
![image](https://user-images.githubusercontent.com/5448638/68828748-c2925680-06e1-11ea-87ec-a3ed1b639f2c.png)

**Comment by EryouHao** [comment]
如果可以移植一份可以收录 😂
